name: CI
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  quick-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: zip -r ktrhfs-app-src.zip . -x ".git/*" ".github/*" "dist/*" "*.asv" "*.mex*" "*~" ".DS_Store"
      - uses: actions/upload-artifact@v4
        with:
          name: ktrhfs-app-src
          path: ktrhfs-app-src.zip
          retention-days: 7

  decide-matlab:
    runs-on: ubuntu-latest
    outputs:
      enable: ${{ steps.chk.outputs.enable }}
    steps:
      - id: chk
        env:
          HAS: ${{ secrets.MATLAB_LICENSE_FILE || secrets.MATLAB_TOKEN }}
        run: |
          if [ -n "${HAS}" ]; then echo "enable=true" >> $GITHUB_OUTPUT; else echo "enable=false" >> $GITHUB_OUTPUT; fi

  matlab-build:
    needs: decide-matlab
    if: ${{ needs.decide-matlab.outputs.enable == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: matlab-actions/setup-matlab@v2
      - uses: matlab-actions/run-command@v2
        with:
          command: build/build
      - uses: actions/upload-artifact@v4
        with:
          name: matlab-build-output
          path: build/output/**
          retention-days: 7

