# .github/workflows/ci.yml
name: CI
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  quick-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: zip -r ktrhfs-app-src.zip . -x ".git/*" ".github/*" "dist/*" "*.asv" "*.mex*" "*~" ".DS_Store"
      - uses: actions/upload-artifact@v4
        with:
          name: ktrhfs-app-src
          path: ktrhfs-app-src.zip

  matlab-build:
    runs-on: ubuntu-latest
    env:
      HAS_MATLAB: ${{ secrets.MATLAB_LICENSE_FILE || secrets.MATLAB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: Skip MATLAB build (no secrets configured)
        if: ${{ !env.HAS_MATLAB }}
        run: |
          echo "MATLAB build not configured. Set MATLAB_LICENSE_FILE or MATLAB_TOKEN to enable."
          exit 0
      - uses: matlab-actions/setup-matlab@v2
      - uses: matlab-actions/run-command@v2
        with:
          command: |
            disp('MATLAB is available. Replace this with your real build.')
            exit(0)

