name: CI

on:
  push:
  pull_request:

jobs:
  # Fast, license-free job for demos/screenshots
  quick-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Show basic repo info (for logs)
        run: |
          echo "Repo: $GITHUB_REPOSITORY"
          echo "Branch: $GITHUB_REF_NAME"
          echo "Commit: $GITHUB_SHA"
          echo "Files:"
          ls -la

      - name: Create source bundle (zip)
        run: |
          zip -r ktrhfs-app-src.zip . \
            -x ".git/*" ".github/*" "build/*" "*.asv" "*.mex*" "*~" ".DS_Store"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ktrhfs-app-src
          path: ktrhfs-app-src.zip
          retention-days: 7

  # (Optional) Real MATLAB build, guarded by a secret so it doesn't run until you're ready
  matlab-build:
    if: ${{ secrets.MATLAB_LICENSE_FILE != '' || secrets.MATLAB_TOKEN != '' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2

      - name: Run MATLAB build
        uses: matlab-actions/run-command@v2
        with:
          command: build/build

      - name: Upload build outputs
        uses: actions/upload-artifact@v4
        with:
          name: matlab-build-output
          path: build/output/**
          retention-days: 7

